artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  https://huggingface.co/datasets/samsum/1.0.0/archive
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion